const topics=[
  ['Понятие дроби','Дроби',25],['Сокращение дробей','Дроби',33],['Сравнение дробей','Дроби',20],['Сложение дробей','Дроби',33],
  ['Вычитание дробей','Дроби',0],['Умножение дробей','Дроби',0],['Деление дробей','Дроби',0],['Смешанные числа','Дроби',0],
  ['Пропорции','Отношения',40],['Проценты','Отношения',15],['Координатная плоскость','Геометрия',0],['Площадь фигур','Геометрия',50]
];
const names={home:'Мой маршрут',map:'Карта знаний',diagnostic:'Диагностика',teacher:'Преподавателю',library:'Учебные материалы',settings:'Подключение AI'};
let state=JSON.parse(localStorage.getItem('vektor-progress')||'{"answers":13,"checked":12,"mastered":0}');
const save=()=>localStorage.setItem('vektor-progress',JSON.stringify(state));
const app=document.querySelector('#app');
function shell(title,sub,body){return `<div class="heading"><div><h1>${title}</h1><p class="sub">${sub}</p></div><span class="pill">✧ Математика · 5–6 классы</span></div>${body}`}
function home(){return shell('Хороший день, чтобы понять новое','Маленькие шаги, понятные объяснения и твой собственный темп.',`<div class="layout"><section><div class="hero"><div class="eyebrow">ТВОЙ СЛЕДУЮЩИЙ ШАГ</div><h2>Понятие дроби</h2><p>Дробь описывает часть целого, разделённого на равные части.</p><button class="primary" data-start="0">Начать занятие →</button><span class="meta">◷ 5–10 минут</span><div class="sculpture"></div></div><div class="stats"><div class="stat"><small>Навыков освоено</small><strong>${state.mastered}<span>/ 24</span></strong></div><div class="stat"><small>Ответов записано</small><strong>${state.answers}</strong></div><div class="stat"><small>Проверено навыков</small><strong>${state.checked}<span>/ 24</span></strong></div></div><div class="section-title"><h2>Ближайшие шаги</h2><button class="textbtn" data-go="map">Вся карта ↗</button></div><div class="card path">${[0,1,3,7].map(i=>row(i)).join('')}</div><div class="card pad" style="margin-top:20px"><h3>Библиотека стала больше</h3><p class="sub">24 микроурока · 480 упражнений · 6 разделов</p><button class="textbtn" data-go="library">Выбрать тему →</button></div></section><section class="right"><div class="card pad"><h3>Твоя картина знаний</h3><div class="ring" style="--v:32"><div>32%<small>по проверенным навыкам</small></div></div><p class="notice">Это учебный индикатор, не оценка за весь курс. Непроверенные темы не считаются пробелами.</p><button class="primary" data-go="diagnostic">Уточнить диагностику</button><p class="notice">До 12 вопросов · без подсказок</p></div><div class="card pad tip"><div class="eyebrow">✧ НАСТАВНИК</div><h3>AI подключён</h3><p>Обсуждай текущую задачу с наставником прямо в занятии.</p><button class="textbtn" data-go="settings">Настройки →</button></div></section></div>`)}
function row(i){let t=topics[i];return `<div class="pathrow"><div class="node">○</div><div><h3>${t[0]}</h3><small>${t[1]} · ${t[2]?t[2]+'%':'Не проверено'}</small></div><button class="textbtn" data-start="${i}">Открыть →</button></div>`}
function mapPage(){return shell('Карта знаний','Вся программа перед глазами: выбирай тему и двигайся в своём темпе.',`<div class="grid">${topics.map((t,i)=>`<div class="card skill"><div class="num">${String(i+1).padStart(2,'0')} · ${t[1]}</div><h3>${t[0]}</h3><p>${t[2]?'Ты уже начал эту тему. Продолжай с того места, где остановился.':'Готово к изучению, когда захочешь сделать следующий шаг.'}</p><div class="progress"><i style="width:${t[2]}%"></i></div><button class="textbtn" data-start="${i}">${t[2]?'Продолжить':'Начать'} →</button></div>`).join('')}</div>`)}
function lesson(i){let t=topics[i];return shell(t[0],`${t[1]} · короткое занятие`,`<div class="lesson-grid"><section class="card task"><div class="eyebrow">РАЗБЕРЁМ НА ПРИМЕРЕ</div><p>Представь пиццу, разделённую на 8 равных частей. Три части уже съели.</p><div class="question">Какая часть пиццы осталась?</div><input id="answer" placeholder="например, 5/8"><div class="actions"><button class="primary" id="check">Проверить ответ</button><button class="secondary" data-go="map">Вернуться к карте</button></div><div id="feedback"></div></section><aside class="card pad tutor" style="position:static;width:auto"><div class="eyebrow">✧ НАСТАВНИК</div><h3>Нужна подсказка?</h3><p class="bubble">Всего было 8 частей. Сначала найди, сколько осталось, а затем запиши это число над общим количеством частей.</p></aside></div>`)}
function diagnostic(){return shell('Диагностика','Несколько спокойных вопросов помогут точнее подобрать маршрут.',`<div class="card task"><div class="eyebrow">ВОПРОС 1 ИЗ 3</div><p>Вычисли:</p><div class="question">3/4 + 1/4 = ?</div><input id="answer" placeholder="твой ответ"><div class="actions"><button class="primary" id="checkDiag">Проверить</button></div><div id="feedback"></div></div>`)}
function teacher(){return shell('Преподавателю','Краткая и честная картина прогресса ученика.',`<div class="stats"><div class="stat"><small>Освоено навыков</small><strong>${state.mastered}<span>/ 24</span></strong></div><div class="stat"><small>Активных тем</small><strong>6</strong></div><div class="stat"><small>Ответов</small><strong>${state.answers}</strong></div></div><div class="card pad"><h3>Рекомендации</h3><table><tr><th>ТЕМА</th><th>НАБЛЮДЕНИЕ</th><th>СЛЕДУЮЩИЙ ШАГ</th></tr><tr><td>Понятие дроби</td><td>Формируется базовое понимание</td><td class="success">Закрепить на моделях</td></tr><tr><td>Сокращение дробей</td><td>Нужна практика</td><td>Повторить общий делитель</td></tr><tr><td>Площадь фигур</td><td>Уверенный навык</td><td class="success">Перейти к составным фигурам</td></tr></table></div>`)}
function library(){return shell('Учебные материалы','Короткие объяснения и примеры — без лишнего шума.',`<div class="filters"><button class="secondary">Все темы</button><button class="secondary">Дроби</button><button class="secondary">Геометрия</button><button class="secondary">Проценты</button></div><div class="grid">${topics.slice(0,6).map((t,i)=>`<div class="card skill"><div class="num">МИКРОУРОК · 5–10 МИНУТ</div><h3>${t[0]}</h3><p>Определение, наглядный пример и несколько заданий для закрепления.</p><button class="textbtn" data-start="${i}">Открыть материал →</button></div>`).join('')}</div>`)}
function settings(){return shell('Подключение AI','Настрой учебного помощника для обсуждения задач.',`<div class="layout"><section class="card pad"><h3>Наставник</h3><p class="notice">В этой копии ответы помощника работают локально и не отправляют данные во внешние сервисы.</p><label class="field">Имя ученика<input value="Александр"></label><label class="field">Стиль объяснения<select><option>Коротко и по шагам</option><option>Через наглядные примеры</option></select></label><button class="primary" id="saveSettings">Сохранить настройки</button><div id="feedback"></div></section><section class="card pad tip"><div class="eyebrow">✧ БЕЗОПАСНО</div><h3>Локальный режим</h3><p>Прогресс сохраняется только в этом браузере.</p></section></div>`)}
function render(page=(location.hash.slice(1)||'home')){if(!names[page])page='home';document.querySelector('#crumb').textContent=names[page];document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));app.innerHTML=({home,map:mapPage,diagnostic,teacher,library,settings}[page]||home)();bind()}
function bind(){document.querySelectorAll('[data-page],[data-go]').forEach(b=>b.onclick=()=>location.hash=b.dataset.page||b.dataset.go);document.querySelectorAll('[data-start]').forEach(b=>b.onclick=()=>{app.innerHTML=lesson(+b.dataset.start);document.querySelector('#crumb').textContent='Занятие';bind()});let check=document.querySelector('#check');if(check)check.onclick=()=>grade(document.querySelector('#answer').value.trim()==='5/8','Верно! Осталось 5 частей из 8 — это 5/8.');let diag=document.querySelector('#checkDiag');if(diag)diag.onclick=()=>grade(['1','1/1'].includes(document.querySelector('#answer').value.trim()),'Точно: четыре четверти составляют одно целое.');let saveBtn=document.querySelector('#saveSettings');if(saveBtn)saveBtn.onclick=()=>document.querySelector('#feedback').innerHTML='<div class="feedback">Настройки сохранены в этом браузере.</div>'}
function grade(ok,text){state.answers++;if(ok)state.mastered=Math.min(24,state.mastered+1);save();document.querySelector('#feedback').innerHTML=`<div class="feedback ${ok?'':'bad'}">${ok?text:'Пока не совпало. Попробуй нарисовать восемь равных частей и зачеркнуть три.'}</div>`}
addEventListener('hashchange',()=>render());render();
